#!/usr/bin/env node
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(scriptDir, '..')
const plotlinePath = join(repoRoot, 'Plotline.json')
const shimPath = join(scriptDir, 'static-api-shim.js')
const distIndexPath = join(repoRoot, 'web', 'dist', 'index.html')
const distShimPath = join(repoRoot, 'web', 'dist', 'static-api.js')
const outputName = 'static-api.js'
const scriptTag = `<script src="/${outputName}" defer></script>`

function fail(message) {
  console.error(`[build-static] ERROR: ${message}`)
  process.exit(1)
}

if (!existsSync(distIndexPath)) {
  fail('web/dist/index.html not found — run the frontend build first (cd web && npm run build).')
}

let plotline
try {
  plotline = JSON.parse(readFileSync(plotlinePath, 'utf8'))
} catch (err) {
  fail(`cannot read Plotline.json: ${err.message}`)
}
if (!Array.isArray(plotline.data) || plotline.data.length === 0) {
  fail('Plotline.json does not contain a non-empty "data" array.')
}

let shim
try {
  shim = readFileSync(shimPath, 'utf8')
} catch (err) {
  fail(`cannot read scripts/static-api-shim.js: ${err.message}`)
}

const banner =
  '/* Generated by scripts/build-static.mjs — do not edit. ' +
  'Regenerated on every static build. */\n'
writeFileSync(distShimPath, `${banner}window.__ARKPLOTS_PLOTLINE__ = ${JSON.stringify(plotline)};\n${shim}`)

let html = readFileSync(distIndexPath, 'utf8')
if (!html.includes(`/${outputName}`)) {
  // Insert before the first <script> tag (document order decides execution
  // order among deferred scripts); fall back to </head> if none exists.
  const firstScript = html.search(/<script[\s>]/)
  const headClose = html.lastIndexOf('</head>')
  let insertAt = firstScript !== -1 ? firstScript : headClose
  if (insertAt === -1) {
    fail('no <script> tag or </head> found in web/dist/index.html — cannot inject the shim.')
  }
  const lineStart = html.lastIndexOf('\n', insertAt) + 1
  const indent = html.slice(lineStart, insertAt)
  html = `${html.slice(0, lineStart)}${indent}${scriptTag}\n${html.slice(lineStart)}`
  writeFileSync(distIndexPath, html)
}

console.log(
  `[build-static] wrote web/dist/${outputName} (${plotline.data.length} plots inlined) ` +
    `and ensured the script tag in web/dist/index.html.`
)
